In [2]:
# !pip install torch torchvision

In [3]:
import numpy as np
import torch

In [6]:
scalar = torch.tensor(12)
scalar

tensor(12)

In [8]:
type(scalar) # skaler, vektör, matrix, tensör -- hepsinin type tensor olur.

torch.Tensor

In [9]:
scalar + 3

tensor(15)

In [10]:
scalar//2

tensor(6)

In [11]:
scalar * 33

tensor(396)

In [13]:
scalar.dim() # 0 dimension çünkü skalar

0

In [14]:
scalar.shape

torch.Size([])

In [15]:
scalar.dtype

torch.int64

In [17]:
vektor = torch.tensor(33, dtype = torch.int32) # default dtype torch.int64

In [18]:
vektor

tensor(33, dtype=torch.int32)

In [21]:
tensor_float = torch.tensor(3.14)
tensor_float

tensor(3.1400)

In [22]:
tensor_float.dtype

torch.float32

### Vectors

In [23]:
vector = torch.tensor([2, 3])
vector

tensor([2, 3])

In [29]:
vector.ndim # 1 dimensional

1

In [30]:
vector.shape

torch.Size([2])

Boyut sayısını belirlemek için köşeli parantez sayısına bakılır.
Shape belirlemek için her boyuttaki eleman sayısına bakılır.

In [32]:
vector2 = torch.tensor([2,3,4,5,12])
vector2.shape

torch.Size([5])

In [33]:
vector2.dim()

1

### Markdown

In [34]:
matrix = torch.tensor([[2, 3], [3, 5]])
matrix

tensor([[2, 3],
        [3, 5]])

In [36]:
matrix.dtype

torch.int64

In [37]:
matrix.shape

torch.Size([2, 2])

In [38]:
matrix.dim()

2

### Tensor

In [39]:
tensor = torch.tensor([[[1,2,3],[1,2,3],[3,4,1]],[[1,2,3],[2,9,7],[2,2,5]]])

In [40]:
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [3, 4, 1]],

        [[1, 2, 3],
         [2, 9, 7],
         [2, 2, 5]]])

In [41]:
tensor.dim()

3

In [42]:
tensor.shape

torch.Size([2, 3, 3])

In [43]:
tensor2 = torch.tensor([[[1,2,3],[1,2,3],[3,4,1]],[[1,2,3],[2,9,7],[2,2,5]],[[1,2,3],[1,2,3],[3,4,1]]])

In [44]:
tensor2.shape

torch.Size([3, 3, 3])

In [49]:
tensor3 = torch.tensor([[[1,3],[1,2],[4,1]]])

In [50]:
tensor3.shape

torch.Size([1, 3, 2])

In [54]:
float_16_tensor = torch.tensor(
    [3.2, 5.0, 3.0],
    dtype = torch.float16, # default or custom?
    device = None, # cpu or gpu?
    requires_grad = False  # öğrenme olacak mı?
)

In [57]:
float_16_tensor.dim()

1

In [58]:
float_16_tensor.dtype

torch.float16