In [3]:
import torch

In [4]:
tensor = torch.arange(1,51,6)

In [5]:
tensor

tensor([ 1,  7, 13, 19, 25, 31, 37, 43, 49])

In [6]:
tensor.min()

tensor(1)

In [7]:
tensor.max()

tensor(49)

In [8]:
tensor.argmin()  # min indeksi

tensor(0)

In [9]:
tensor.argmax()  # max indeksi

tensor(8)

In [10]:
tensor.argmax().item()

8

In [11]:
tensor[3]

tensor(19)

In [12]:
tensor.sum()

tensor(225)

In [13]:
tensor.median()

tensor(25)

In [14]:
tensor.mean()  # hatanın sebebi: Tensor lon veri tipinin (int64) mean alamıyor.

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [15]:
tensor.dtype

torch.int64

In [16]:
tensor.type(torch.float).mean()

tensor(25.)

In [17]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [18]:
matrix[0]

tensor([1, 2, 3])

In [19]:
matrix[0][2]

tensor(3)

In [20]:
matrix[0][2].item()

3

## Manipulating Tensors: reshaping, stacking, squeezing, unsqueezing

#### Reshape 

In [25]:
x = torch.arange(1,10)

In [26]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x.shape


torch.Size([9])

In [30]:
x.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
x.reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
x.reshape(2,5)

RuntimeError: shape '[2, 5]' is invalid for input of size 9

In [35]:
x_reshaped = x.reshape(9,1)

In [36]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [42]:
x_view = x.view(3,3)  # reshape ile yüzde 99 aynı

In [43]:
x_view

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
x_view.view(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [45]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

they both change the original tensor if there is a change in them. Hhowever view only works with contigious tensors

In [85]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [50]:
x.is_contiguous()  # arka arkaya saklanıyor mu?

True

In [53]:
x.reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [55]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [56]:
y = x.T

In [57]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [58]:
y.is_contiguous()

False

In [61]:
y.view(1,6)  # hata çünkü contiguous değil

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [62]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

#### Stacking

In [63]:
x 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [64]:
torch.stack([x,x,x,x])

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [66]:
torch.stack([x,x,x,x], dim=1)  # çok karşına çıkmaz

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [71]:
torch.stack([x,x,x,x], dim=2)  

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]]])

#### squeeze & unsqueeze

squeeze, yapabiliyorsa gereksiz boyutu atar. Unsqueeze ise boyut ekler.

In [72]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [73]:
x.ndim

2

In [75]:
x.squeeze() # aynı kaldı çünkü fazladan boyut yok

tensor([[1, 2, 3],
        [4, 5, 6]])

In [77]:
x.squeeze().ndim

2

In [78]:
y = torch.tensor([[[1,2,3,4]]])

In [79]:
y

tensor([[[1, 2, 3, 4]]])

In [80]:
y.ndim

3

In [81]:
y.squeeze()

tensor([1, 2, 3, 4])

In [82]:
y.squeeze().ndim

1

In [86]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [96]:
x.unsqueeze(dim=0)  # başa bir boyut ekledi. 

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [99]:
x.unsqueeze(dim=1) 

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

- dim=0: (1, A, B) -> Veriyi bir "paket" içine koyar (Batch eklemek gibi).

- dim=1: (A, 1, B) -> Satırlar arasına bir derinlik ekler.

- dim=2: (A, B, 1) -> Her sütun verisini kendi içinde bir boyuta hapseder.

- dim=0 (En Başa Ekleme)
    Yeni boyutu en dışa ekler. Bu genellikle "Batch Size" (yığın boyutu) eklemek için kullanılır.

    İşlem: x.unsqueeze(0)

    Sonuç: (1, 3, 4)

    Anlamı: "Elimde 3x4'lük veriden oluşan 1 adet paket var."

    Görünüm: [ [ [...] ] ]

- dim=-1 (En Sona Ekleme)
    -1 her zaman "sonuncu" demektir. Yeni boyutu en içe ekler.

    İşlem: x.unsqueeze(-1)
    
    Sonuç: (3, 4, 1)

    Görünüm: [ [ [.], [.] ] ]

#### Permute

rearrange the order of axes values

In [100]:
x = torch.rand(size=(224, 224, 3))

In [102]:
x.shape

torch.Size([224, 224, 3])

In [103]:
x_permuted = x.permute(2, 0, 1)  # 0. indekse 2dekini yaz, 1. indekse 0dakini yaz, 2. indekse 1.yi yaz

In [104]:
x_permuted.shape

torch.Size([3, 224, 224])

#### indexing & slicing

In [112]:
a =torch.arange(1,10,1)

In [113]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
b = a.reshape(3,3)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [117]:
c = a.reshape(1,3,3)  # fazladan bir dim ekledik. unsqueeze gibi
c

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [118]:
c[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [119]:
c[0][0]

tensor([1, 2, 3])

In [120]:
c[0][0][0]

tensor(1)

In [130]:
c.shape

torch.Size([1, 3, 3])

In [131]:
c

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [121]:
# Get all values of 0th dimension and the 0 index of 1st dimension
c[:, 0]

tensor([[1, 2, 3]])

In [123]:
c[:, 0]

tensor([[1, 2, 3]])

In [124]:
c[:,0,0]

tensor([1])

--- shapei 1 olan dimensionlara : koyabiliriz direkt. 

In [132]:
c[:, :, 2]  # 2. indeksteki columnu aldık

tensor([[3, 6, 9]])

In [133]:
c[:, 2, :]  # 2. indeksteki rowu aldık

tensor([[7, 8, 9]])

In [134]:
c[0,0,:]

tensor([1, 2, 3])

In [135]:
c[0,:,0]

tensor([1, 4, 7])

#### random seeds

In [143]:
random_tensor = torch.rand(3, 4)  # her çalıştırışta farklı random sayılar gelir.
random_tensor

tensor([[0.8304, 0.3195, 0.4456, 0.3613],
        [0.7174, 0.7494, 0.3417, 0.4968],
        [0.3456, 0.2663, 0.8453, 0.1845]])

In [150]:
torch.manual_seed(31)  # bu satır ile birlikte her seferinde aynı random sayıların gelmesini sağlar.
tensor = torch.rand(3,4)
tensor

tensor([[0.2298, 0.4218, 0.2750, 0.5173],
        [0.2001, 0.5276, 0.6387, 0.4844],
        [0.2904, 0.3001, 0.0508, 0.3926]])