In [2]:
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("06-study_hours_grades.csv")

In [4]:
df.head()

,study_hours,grade
0,3.745401,30.203939
1,9.507143,57.878452
2,7.319939,46.368401
3,5.986585,39.330717
4,1.560186,14.843888


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  50 non-null     float64
 1   grade        50 non-null     float64
dtypes: float64(2)
memory usage: 932.0 bytes


In [6]:
df["study_hours"].values  # bu numpy arrayi olarak saklanıyor.

array([3.74540119, 9.50714306, 7.31993942, 5.98658484, 1.5601864 ,
       1.5599452 , 0.58083612, 8.66176146, 6.01115012, 7.08072578,
       0.20584494, 9.69909852, 8.32442641, 2.12339111, 1.81824967,
       1.8340451 , 3.04242243, 5.24756432, 4.31945019, 2.9122914 ,
       6.11852895, 1.39493861, 2.92144649, 3.66361843, 4.56069984,
       7.85175961, 1.99673782, 5.14234438, 5.92414569, 0.46450413,
       6.07544852, 1.70524124, 0.65051593, 9.48885537, 9.65632033,
       8.08397348, 3.04613769, 0.97672114, 6.84233027, 4.40152494,
       1.22038235, 4.9517691 , 0.34388521, 9.09320402, 2.58779982,
       6.62522284, 3.11711076, 5.20068021, 5.46710279, 1.84854456])

In [7]:
torch.tensor(df["study_hours"].values)  

tensor([3.7454, 9.5071, 7.3199, 5.9866, 1.5602, 1.5599, 0.5808, 8.6618, 6.0112,
        7.0807, 0.2058, 9.6991, 8.3244, 2.1234, 1.8182, 1.8340, 3.0424, 5.2476,
        4.3195, 2.9123, 6.1185, 1.3949, 2.9214, 3.6636, 4.5607, 7.8518, 1.9967,
        5.1423, 5.9241, 0.4645, 6.0754, 1.7052, 0.6505, 9.4889, 9.6563, 8.0840,
        3.0461, 0.9767, 6.8423, 4.4015, 1.2204, 4.9518, 0.3439, 9.0932, 2.5878,
        6.6252, 3.1171, 5.2007, 5.4671, 1.8485], dtype=torch.float64)

In [8]:
x = torch.tensor(df["study_hours"].values)
y = torch.tensor(df["grade"].values)

In [9]:
x

tensor([3.7454, 9.5071, 7.3199, 5.9866, 1.5602, 1.5599, 0.5808, 8.6618, 6.0112,
        7.0807, 0.2058, 9.6991, 8.3244, 2.1234, 1.8182, 1.8340, 3.0424, 5.2476,
        4.3195, 2.9123, 6.1185, 1.3949, 2.9214, 3.6636, 4.5607, 7.8518, 1.9967,
        5.1423, 5.9241, 0.4645, 6.0754, 1.7052, 0.6505, 9.4889, 9.6563, 8.0840,
        3.0461, 0.9767, 6.8423, 4.4015, 1.2204, 4.9518, 0.3439, 9.0932, 2.5878,
        6.6252, 3.1171, 5.2007, 5.4671, 1.8485], dtype=torch.float64)

In [10]:
y

tensor([30.2039, 57.8785, 46.3684, 39.3307, 14.8439, 16.3600, 11.9829, 55.4231,
        40.7430, 41.8775, 11.6774, 57.7253, 50.2683, 21.8403, 21.1532, 21.0328,
        23.5337, 35.6194, 32.2598, 26.5125, 39.6343, 16.6034, 22.3946, 25.9257,
        34.4286, 51.9713, 19.8397, 37.7188, 40.3440, 11.0323, 41.1000, 21.6023,
        13.1809, 60.5736, 53.0421, 52.0637, 25.4048, 14.2856, 44.3952, 28.0325,
        15.6626, 35.4731, 14.6752, 54.4295, 21.3220, 42.1226, 27.4164, 36.6609,
        36.2760, 20.2693], dtype=torch.float64)

In [11]:
split = int(0.8 * len(x))
x_train, y_train = x[:split], y[:split]
x_test, y_test = x[split:], y[split:]

In [12]:
"""

plt.scatter(x_train, y_train, c="b", s=5, marker = "o")
plt.scatter(x_test, y_test, c="purple", s=5, marker = "x")

plt.show()

"""

'\n\nplt.scatter(x_train, y_train, c="b", s=5, marker = "o")\nplt.scatter(x_test, y_test, c="purple", s=5, marker = "x")\n\nplt.show()\n\n'

data hazır şimdi öğrenme aşamasına geçelim.

### Manual Learning 

In [13]:
from torch import nn

In [14]:
class SimpleLinearRegressionModel(nn.Module): # inheriting neural network module
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1, dtype=torch.float)) # random weights
        self.bias = nn.Parameter(torch.randn(1, dtype=torch.float))  # random bias

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.weights * x + self.bias

In [15]:
torch.manual_seed(31)

model = SimpleLinearRegressionModel()
model = torch.compile(model)  

In [16]:
list(model.parameters())

[Parameter containing:
 tensor([0.3519], requires_grad=True),
 Parameter containing:
 tensor([-0.5683], requires_grad=True)]

In [17]:
model.state_dict()

OrderedDict([('_orig_mod.weights', tensor([0.3519])),
             ('_orig_mod.bias', tensor([-0.5683]))])

In [30]:
import torch._dynamo
torch._dynamo.config.suppress_errors = True

# compiler hatası alıyordu aşagıdaki kod. onu engellemek için.

In [31]:
# tahmin yapacagız. Başarısız olacak çünkü henüz eğitmedik.

with torch.inference_mode():   # turns off gradient tracking, it is not training.
    y_preds = model(x_test)

In [32]:
len(x_test), len(y_preds)

(10, 10)

### Optimize loss function

In [33]:
mse = nn.MSELoss()
# mae = nn.F1Loss()

# create optimizer
optimizer = torch.optim.SGD(params = model.parameters(), lr = 0.01)

In [34]:
torch.manual_seed(31)

epochs = 200
train_loss_values = []
test_loss_values = []
epoch_counts = []

for epoch in range(epochs):
    model.train()

    y_pred = model(x_train)  # training data using forward()
    loss = mse(y_pred, y_train) 
    optimizer.zero_grad()  # optimizer gradient numbers accumulate every epoch, we need to reset it
    loss.backward()
    optimizer.step()  # optimize weights

    with torch.inference_mode():
        test_pred = model(x_test)
        test_loss = mse(test_pred, y_test.type(torch.float))

        if epoch % 5 == 0:
            epoch_counts.append(epoch)
            test_loss_values.append(test_loss.detach().numpy())
            train_loss_values.append(loss.detach().numpy())
            print(f"Epoch: {epoch} |  Train Loss: {loss} | Test Loss: {test_loss} ")

Epoch: 0 |  Train Loss: 6.335136059934942 | Test Loss: 7.232290435732867 
Epoch: 5 |  Train Loss: 6.185547501672595 | Test Loss: 7.013216513532278 
Epoch: 10 |  Train Loss: 6.0442309258209885 | Test Loss: 6.804382413838456 
Epoch: 15 |  Train Loss: 5.910727360321273 | Test Loss: 6.605272331018066 
Epoch: 20 |  Train Loss: 5.784605081088926 | Test Loss: 6.415400839131348 
Epoch: 25 |  Train Loss: 5.66545675512473 | Test Loss: 6.234306571593975 
Epoch: 30 |  Train Loss: 5.552896473403824 | Test Loss: 6.061553538501834 
Epoch: 35 |  Train Loss: 5.446559869812232 | Test Loss: 5.89672610972571 
Epoch: 40 |  Train Loss: 5.346103188514069 | Test Loss: 5.739432415951261 
Epoch: 45 |  Train Loss: 5.251201768853588 | Test Loss: 5.5893007400229076 
Epoch: 50 |  Train Loss: 5.161546948272927 | Test Loss: 5.445976864756094 
Epoch: 55 |  Train Loss: 5.076848831692029 | Test Loss: 5.309126099327328 
Epoch: 60 |  Train Loss: 4.996834179725565 | Test Loss: 5.178431610264728 
Epoch: 65 |  Train Loss: 4.

In [35]:

# Plot the loss curves
"""
plt.plot(epoch_count, train_loss_values, label="Train loss")
plt.plot(epoch_count, test_loss_values, label="Test loss")
plt.title("Training and test loss curves")
plt.ylabel("Loss")
plt.xlabel("Epochs")
plt.show()
"""

'\nplt.plot(epoch_count, train_loss_values, label="Train loss")\nplt.plot(epoch_count, test_loss_values, label="Test loss")\nplt.title("Training and test loss curves")\nplt.ylabel("Loss")\nplt.xlabel("Epochs")\nplt.show()\n'

In [36]:
print(model.state_dict())

OrderedDict([('_orig_mod.weights', tensor([5.1595])), ('_orig_mod.bias', tensor([8.9366]))])


In [37]:
model.eval()
with torch.inference_mode():
    tahmin = model(x_test)

In [38]:
tahmin

tensor([15.2332, 34.4854, 10.7109, 55.8533, 22.2885, 43.1197, 25.0195, 35.7697,
        37.1443, 18.4742], dtype=torch.float64)

In [39]:
y_test

tensor([15.6626, 35.4731, 14.6752, 54.4295, 21.3220, 42.1226, 27.4164, 36.6609,
        36.2760, 20.2693], dtype=torch.float64)

In [40]:
"""
plt.scatter(X_train, y_train, c="b", s=4, label="Training data")
plt.scatter(X_test, y_test, c="g", s=4, label="Testing data")
plt.scatter(X_test, tahmin, c="r", s=4, label="Predictions")
plt.show()
"""

'\nplt.scatter(X_train, y_train, c="b", s=4, label="Training data")\nplt.scatter(X_test, y_test, c="g", s=4, label="Testing data")\nplt.scatter(X_test, tahmin, c="r", s=4, label="Predictions")\nplt.show()\n'