In [1]:
import numpy as np
import torch

In [2]:
random = np.random.randn(3,5)
random

array([[ 0.75434568,  0.26156523,  1.07703815, -1.14472539,  0.56423815],
       [-0.62883354,  0.07916639, -0.42692348, -0.26250689, -1.42682031],
       [-0.71848621, -0.66911795, -0.90958289,  0.35883898, -1.06318425]])

In [3]:
random.ndim

2

In [4]:
random.dtype

dtype('float64')

In [8]:
random.shape

(3, 5)

In [5]:
matrix = torch.rand(size = (3, 5))
matrix

tensor([[0.5308, 0.3701, 0.3561, 0.4960, 0.3997],
        [0.3931, 0.3725, 0.2444, 0.6065, 0.7647],
        [0.0362, 0.3952, 0.0308, 0.3471, 0.0459]])

In [6]:
matrix.ndim

2

In [7]:
matrix.dtype

torch.float32

In [9]:
matrix.shape

torch.Size([3, 5])

we generally use 32 * 32 or 224 * 224 images in vision dl problems

In [13]:
img_matrix = torch.rand(size=(224,224,3))

In [14]:
img_matrix

tensor([[[0.5399, 0.9248, 0.8017],
         [0.6866, 0.9176, 0.6987],
         [0.1525, 0.3256, 0.1291],
         ...,
         [0.1301, 0.8752, 0.5161],
         [0.8483, 0.4713, 0.7780],
         [0.9831, 0.3484, 0.8589]],

        [[0.5515, 0.9647, 0.9073],
         [0.1233, 0.3471, 0.1986],
         [0.0975, 0.4337, 0.6987],
         ...,
         [0.2519, 0.5805, 0.6957],
         [0.2749, 0.2630, 0.6499],
         [0.9641, 0.4025, 0.2007]],

        [[0.0406, 0.4680, 0.3661],
         [0.3288, 0.6151, 0.0234],
         [0.1616, 0.5457, 0.1988],
         ...,
         [0.7562, 0.0917, 0.6930],
         [0.5679, 0.2207, 0.5005],
         [0.4386, 0.5909, 0.3609]],

        ...,

        [[0.6509, 0.6966, 0.6876],
         [0.2306, 0.2930, 0.9768],
         [0.2519, 0.2482, 0.1946],
         ...,
         [0.8378, 0.3552, 0.1855],
         [0.6894, 0.6118, 0.7328],
         [0.9728, 0.3069, 0.6671]],

        [[0.5959, 0.2905, 0.8227],
         [0.9326, 0.9633, 0.5545],
         [0.

In [16]:
img_matrix.shape

torch.Size([224, 224, 3])

In [17]:
img_matrix.ndim

3

### Operations

In [22]:
torch.ones(3,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [23]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [24]:
vector_range = torch.arange(start = 3, end = 24, step = 4)

In [25]:
vector_range

tensor([ 3,  7, 11, 15, 19, 23])

In [29]:
similar_ones = torch.ones_like(input=vector_range)  # ones_like input shapeinde 1ler matrisi oluşturur

In [30]:
similar_ones

tensor([1, 1, 1, 1, 1, 1])

In [31]:
t = torch.tensor([1,2,3])

In [32]:
t

tensor([1, 2, 3])

In [33]:
t * 2

tensor([2, 4, 6])

In [34]:
t + 3

tensor([4, 5, 6])

In [35]:
t / 1.5

tensor([0.6667, 1.3333, 2.0000])

Aynı zamanda bunlar için native fonksiyonlarımız da var.

In [36]:
t.multiply(2)

tensor([2, 4, 6])

In [37]:
t.add(3)

tensor([4, 5, 6])

In [38]:
t.divide(1.5)

tensor([0.6667, 1.3333, 2.0000])

In [40]:
t.subtract(8)

tensor([-7, -6, -5])

In [41]:
t * t

tensor([1, 4, 9])

In [42]:
t.multiply(t)

tensor([1, 4, 9])

In [43]:
x = torch.tensor([2,3])

In [44]:
t * x  # 

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0