## Intro Numpy

In [1]:
import numpy  as np

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
arr = np.array([3,4,5,6])

In [8]:
type(arr)

numpy.ndarray

In [35]:
arr2 = np.random.randint(1,21,4)

In [36]:
arr2

array([ 2,  4,  2, 10])

In [15]:
arr + arr2 

array([14, 22, 23, 13])

In [16]:
arr2 - arr

array([ 8, 14, 13,  1])

In [17]:
arr * arr2

array([33, 72, 90, 42])

In [21]:
np.arange(14,72,3)

array([14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62,
       65, 68, 71])

In [23]:
arr2.max()

18

In [24]:
arr2.min()

7

In [25]:
arr2.sum()

54

In [26]:
arr2.mean()

13.5

In [38]:
liste = np.random.random(5)

In [39]:
liste

array([0.41811568, 0.26391631, 0.01403671, 0.46853406, 0.00811551])

In [40]:
liste[::-1]

array([0.00811551, 0.46853406, 0.01403671, 0.26391631, 0.41811568])

In [41]:
liste[1:3]

array([0.26391631, 0.01403671])

## Numpy Matrices

In [79]:
bir = np.array([[2,3],[3,2],[4,5]])
bir

array([[2, 3],
       [3, 2],
       [4, 5]])

In [83]:
iki = np.random.random((2,3))

In [84]:
iki

array([[0.67677569, 0.95015069, 0.08454018],
       [0.69729921, 0.98107766, 0.83729005]])

In [85]:
bir * iki # farklı shape (hata verir)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [86]:
dot  = iki.dot(bir)
dot

array([[4.5421642 , 4.35332938],
       [7.68699161, 8.24050321]])

In [87]:
bir.shape

(3, 2)

In [70]:
iki.shape

(2, 3)

In [68]:
dot.shape

(3, 3)

In [88]:
m = np.zeros((3,4))

In [98]:
n = np.ones((3,1))

In [99]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
n

array([[1.],
       [1.],
       [1.]])

In [102]:
m + n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [103]:
m * n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
deneme = np.random.randint(1,20,4)

In [110]:
deneme

array([19, 19,  8,  2])

In [114]:
deneme2 = np.random.randint(1, 20, size=(2, 3)) 
deneme2

array([[10,  1,  8],
       [ 9,  9,  6]])

In [116]:
deneme3  = np.random.randint(1,20,6)
deneme3

array([12,  4,  9, 18,  2, 19])

In [117]:
deneme3.reshape(3,2)

array([[12,  4],
       [ 9, 18],
       [ 2, 19]])

In [119]:
deneme2.transpose()

array([[10,  9],
       [ 1,  9],
       [ 8,  6]])

In [ ]:
# 2x + 3y = 8 , 5x + 7y = 17

In [129]:
coef = np.array([[2,3],[5,7]])
coef

array([[2, 3],
       [5, 7]])

In [130]:
const = np.array([8,17])
const

array([ 8, 17])

In [131]:
solution = np.linalg.solve(coef,const)
solution

array([-5.,  6.])